config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      registrations: "users/registrations"
    }

  root to: 'pages#home'

  resources :flats do
    get "visits" => "flats#visits" # Visits for landlords
    get "candidates" => "flats#candidates"
    patch "filter" => "flats#filter"
    get "etat_des_lieux" => "flats#etat_des_lieux"

    resources :slots, only: [:create, :update, :destroy] do
      patch "slot_confirm" => "slots#slot_confirm"
      patch "slot_cancel" => "slots#slot_cancel"
    end

    resources :bookings, only: [] do
      patch "booking_confirm" => "bookings#booking_confirm"
      patch "booking_cancel" => "bookings#booking_cancel"
      resources :documents, only: [:show, :index, :create, :update]
    end
  end

  resources :searches, only: [:new, :create, :edit, :update]

  get "profile" => "pages#profile"
  get "dashboard" => "pages#dashboard"
  get "visites" => "pages#visites" # Visits for tenants

  mount Attachinary::Engine => "/attachinary"
end

app/models/flat.rb
class Flat < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  belongs_to :landlord, foreign_key: :landlord_id, class_name: "User"
  has_many :slots, dependent: :destroy
  has_many :bookings, dependent: :destroy

  has_attachments :photos, maximum: 10

  validates :title, :description,  :availability_date, :min_duration, :address, :size, :rent, :rental_costs, :floor, :rooms, :bedrooms, presence: true
  validates :status, presence: true, inclusion: { in: ["Available","Busy"] }
  validates :rental_type, presence: true, inclusion: { in: ["Colocation","Location"] }
end

app/helpers/flats_helper.rb
module FlatsHelper
  def set_flat_image(flat)
    flat.photos.size == 0 ? cl_image_tag(asset_path('default_flat.png')) : cl_image_tag(flat.photos.first.path, :alt => "banner_image", height:300, width: 720, crop: :fill)
  end

  def set_number(string)
    a = string.split
    "#{a[1]} (#{a[0]})"
  end
end

app/views/flats/modals/_modal_confirmation.html.erb
<div class="modal fade" tabindex="-1" role="dialog" id="modal-confirmation">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Confirmez votre choix !</h4>
      </div>

        <% if !candidate.bookings.where(flat: @flat).first.nil? && candidate.bookings.where(flat: @flat).first.status == "Confirmed" %>


            <div class="modal-body">
              <p>Vous êtes sur le point d'annuler cette réservation.</p>
              <p>Si vous confirmez, vous pourrez changer de locataire.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

              <%= simple_form_for [@flat, candidate.bookings.where(flat: @flat).first], url: flat_booking_booking_cancel_path(@flat, candidate.bookings.where(flat: @flat).first), method: :patch do |f| %>
                <%= f.submit "J'annule cette réservation !", class: "btn btn-red" %>
              <% end %>

            </div>

        <% elsif !candidate.bookings.where(flat: @flat).first.nil? && candidate.bookings.where(flat: @flat).first.status == "Pending" %>

            <div class="modal-body">
              <p>Vous êtes sur le point de choisir ce locataire.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

              <%= simple_form_for [@flat, candidate.bookings.where(flat: @flat).first], url: flat_booking_booking_confirm_path(@flat, candidate.bookings.where(flat: @flat).first), method: :patch do |f| %>
                <%= f.submit "Je choisis ce locataire !", class: "btn btn-red" %>
              <% end %>

            </div>

        <% elsif !candidate.slots.where(flat: @flat).first.nil? && candidate.slots.where(flat: @flat).first.starts_at - Time.now > 0 %>

            <div class="modal-body">
              <p>Vous êtes sur le point d'annuler cette visite.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

              <%= simple_form_for [@flat, candidate.slots.where(flat: @flat).first], url: flat_slot_slot_cancel_path(@flat, candidate.slots.where(flat: @flat).first), method: :patch do |f| %>
                <%= f.submit "J'annule cette visite !", class: "btn btn-red" %>
              <% end %>

            </div>

        <% elsif !candidate.slots.where(flat: @flat).first.nil? && candidate.slots.where(flat: @flat).first.starts_at - Time.now <= 0 %>

            <div class="modal-body">
              <p>Vous êtes sur le point de faire une demande de dossier à ce locataire.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

              <%= simple_form_for [@flat, candidate.slots.where(flat: @flat).first], url: flat_slot_slot_cancel_path(@flat, candidate.slots.where(flat: @flat).first) do |f| %>
                <%= f.submit "Je demande le dossier !", class: "btn btn-red" %>
              <% end %>

            </div>

        <% else %>

          <div class="modal-body">
            <p>Vous êtes sur le point de choisir ce locataire.</p>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>

            <%= simple_form_for [@flat, candidate.bookings.where(flat: @flat).first], url: flat_booking_booking_confirm_path(@flat, candidate.bookings.where(flat: @flat).first), method: :patch do |f| %>
              <%= f.submit "Je choisis ce locataire !", class: "btn btn-red" %>
            <% end %>

          </div>

        <% end %>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/flats/modals/_modal_profile.html.erb
<div class="modal fade bs-example-modal-lg" id="modal-profile-<%= candidate.id %>" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title text-center" id="myModalLabel"><strong>Profil de <%= set_fullname(candidate) %></strong></h4>
      </div>

      <div class="modal-body">

        <% if !candidate.bookings.where(flat: @flat).first.nil? && candidate.bookings.where(flat: @flat).first.status == "Confirmed" %>

          <h5>Vous avez choisi <%= set_fullname(candidate) %></h5>
          <h5>pour être le locataire de votre bien.</h5>
          <h5>Vous pouvez changer d'avis et refuser ce dossier</h5>

          <div class="text-center">Note du Dossier : <%= render 'flats/grade', user: candidate, flat: @flat %></div>

          <div><%= image_tag set_user_photo(candidate), class: "card-candidates-user avatar-large-square" %></div>
          <div>Prénom : <%= candidate.first_name %></div>
          <div>Nom : <%= candidate.last_name %></div>
          <div>Situation Professionnelle : <br><%= candidate.status %></div>
          <div><%= candidate.description %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>
            <button type="button" class="btn btn-red" data-toggle="modal" href="#modal-confirmation" data-dismiss="modal">Changez de locataire</button>
          </div>

        <% elsif !candidate.slots.where(flat: @flat).first.nil? && candidate.slots.where(flat: @flat).first.starts_at - Time.now > 0 %>

          <h5><%= set_fullname(candidate) %> n'a pas encore visité.</h5>
          <h5>Vous avez la possibilité d'annuler la visite.</h5>

          <div class="text-center">Note du Dossier : <%= render 'flats/grade', user: candidate, flat: @flat %></div>

          <div><%= image_tag set_user_photo(candidate), class: "card-candidates-user avatar-large-square" %></div>
          <div>Prénom : <%= candidate.first_name %></div>
          <div>Nom : <%= candidate.last_name %></div>
          <div>Situation Professionnelle : <br><%= candidate.status %></div>
          <div><%= candidate.description %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>
            <button type="button" class="btn btn-danger" data-toggle="modal" href="#modal-confirmation" data-dismiss="modal">Annuler la visite</button>
          </div>

        <% elsif !candidate.bookings.where(flat: @flat).first.nil? && candidate.bookings.where(flat: @flat).first.status == "Pending" %>

          <h5><%= set_fullname(candidate) %> est intéressé par votre bien.</h5>
          <h5>Il attend que vous choisissiez ce dossier pour devenir votre locataire. </h5>

          <div class="text-center">Note du Dossier : <%= render 'flats/grade', user: candidate, flat: @flat %></div>

          <div><%= image_tag set_user_photo(candidate), class: "card-candidates-user avatar-large-square" %></div>
          <div>Prénom : <%= candidate.first_name %></div>
          <div>Nom : <%= candidate.last_name %></div>
          <div>Situation Professionnelle : <br><%= candidate.status %></div>
          <div><%= candidate.description %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>
            <button type="button" class="btn btn-red" data-toggle="modal" href="#modal-confirmation" data-dismiss="modal">Choisir ce locataire</button>
          </div>

        <% elsif !candidate.slots.where(flat: @flat).first.nil? && candidate.slots.where(flat: @flat).first.starts_at - Time.now <= 0 %>

          <h5><%= set_fullname(candidate) %> n'a pas encore déposé son dossier après sa visite.</h5>
          <h5>Vous avez la possibilité de lui demander son dossier</h5>

          <div class="text-center">Note du Dossier : <%= render 'flats/grade', user: candidate, flat: @flat %></div>

          <div><%= image_tag set_user_photo(candidate), class: "card-candidates-user avatar-large-square" %></div>
          <div>Prénom : <%= candidate.first_name %></div>
          <div>Nom : <%= candidate.last_name %></div>
          <div>Situation Professionnelle : <br><%= candidate.status %></div>
          <div><%= candidate.description %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>
            <button type="button" class="btn btn-danger" data-toggle="modal" href="#modal-confirmation" data-dismiss="modal">Demander le dossier</button>
          </div>

        <% else %>

          <h5>ERREUR</h5>

          <h5>Vous avez refuser le dossier de <%= set_fullname(user) %></h5>
          <h5>Vous pouvez le recontacter si vous souhaitez.</h5>

          <div class="text-center">Note du Dossier : <%= render 'flats/grade', user: user, flat: @flat %></div>

          <div><%= image_tag set_user_photo(user), class: "card-candidates-user avatar-large-square" %></div>
          <div>Prénom : <%= user.first_name %></div>
          <div>Nom : <%= user.last_name %></div>
          <div>Situation Professionnelle : <br><%= user.status %></div>
          <div><%= user.description %></div>

          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Retour</button>
            <button type="button" class="btn btn-red" data-toggle="modal" href="#modal-confirmation" data-dismiss="modal">Choisir ce locataire</button>
          </div>


        <% end %>

      </div>

    </div>
  </div>
</div>