config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      registrations: "users/registrations"
    }

  root to: 'pages#home'

  resources :flats do
    get "visits" => "flats#visits" # Visits for landlords
    get "candidates" => "flats#candidates"
    patch "filter" => "flats#filter"
    get "etat_des_lieux" => "flats#etat_des_lieux"

    resources :slots, only: [:create, :update, :destroy] do
      patch "slot_confirm" => "slots#slot_confirm"
      patch "slot_cancel" => "slots#slot_cancel"
    end

    resources :bookings, only: [] do
      patch "booking_confirm" => "bookings#booking_confirm"
      patch "booking_cancel" => "bookings#booking_cancel"
      resources :documents, only: [:show, :index, :create, :update]
    end
  end

  resources :searches, only: [:new, :create, :edit, :update]

  get "profile" => "pages#profile"
  get "dashboard" => "pages#dashboard"
  get "visites" => "pages#visites" # Visits for tenants

  mount Attachinary::Engine => "/attachinary"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attachment :photo

  has_many :flats, dependent: :destroy, foreign_key: :landlord_id
  has_many :bookings, dependent: :destroy, foreign_key: :tenant_id
  has_many :slots, dependent: :destroy, foreign_key: :tenant_id
  has_many :searches, dependent: :destroy, foreign_key: :tenant_id

  # validate :has_warrantor_or_not, :warrantor_income_or_not

  def has_warrantor_or_not
    if warrantor_income > 0 and has_warrantor == false
      errors.add(:has_warrantor, "can't be false")
    end
  end

  def warrantor_income_or_not
    if warrantor_income <= 0 and has_warrantor == true
      errors.add(:warrantor_income, "has to be greater than 0")
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  protected

  def update_resource(resource, params)
    resource.update_without_password(params)
  end

  def after_update_path_for(resource)
    if current_user.searches.size == 0
      new_search_path
    else
      edit_search_path(current_user.searches.last)
    end
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show, :new, :edit, :update, :locataire, :recherche, :visites]

  def edit
  end

  def update
    authorize @user
  end

  def locataire
    authorize @user
    # if @user.save
    #   redirect_to user_recherche_path(@user)
    # else
    #   render :new
    # end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
    authorize @user
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def set_user_photo(user)
    user.photo.nil? ? asset_path('default_avatar.png') : cl_image_path(user.photo.public_id, height: 100, width: 100, crop: :fill)
  end

  def set_username(user)
    user.first_name.nil? ? user.email : user.first_name
  end

  def set_fullname(user)
    (user.first_name.nil? || user.last_name.nil?) ? user.email : "#{user.first_name} #{user.last_name}"
  end

  def set_grade(user, flat)

    if (flat.rent + flat.rental_costs) == 0
      grade = 0
    else
      grade = (user.income + (user.warrantor_income * 0.5)) / (flat.rent + flat.rental_costs)
      grade = ((grade * 2).round).fdiv(2)
      if grade >= 5
        grade = 5
      elsif grade <= 0
        grade = 0
      else
        grade
      end
      grade
    end
  end
end

app/views/users/locataire.html.erb
<!-- Locataire navbar -->
<div class="navbar-flat navbar-flat-wagon-fixed">
  <div class="navbar-flat-content">
    <div class="<%= 'active' if current_page?(user_locataire_path(@user)) %>">
      <%= link_to "Mon profil", user_locataire_path(@user), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(user_recherche_path(@user)) %>">
      <%= link_to "Critères de recherche", user_recherche_path(@user), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flats_path) %>">
      <%= link_to "Annonces", flats_path, class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(user_visites_path(@user)) %>">
      <%= link_to "Visites", user_visites_path(@user), class: "navbar-wagon-link" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="card col-xs-12">
      <div class="row">
        <div class="form col-xs-12 col-md-6 col-md-offset-3">
          <h2 class="text-center sm-marged-bottom highlight">Renseigner mon profil</h2>
          <%= simple_form_for(@user, url: user_recherche_path(@user)) do |f| %>
            <%= f.error_notification %>

            <!-- Form inputs -->
            <div class="form-inputs">

              <!-- Gender -->
              <div class="form-group radio_buttons optional user_gender">
                <label class="control-label radio_buttons optional">Vous êtes</label>
                <input type="hidden" name="user[gender]" value="">
                <div class="row text-center">
                  <div class="col-xs-12 col-md-6">
                    <span class="radio tenant-radio-button">
                      <label for="user_gender_un_homme">Un homme</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Un homme" name="user[gender]" id="user_gender_un_homme">
                    </span>
                  </div>
                  <div class="col-xs-12 col-md-6">
                    <span class="radio tenant-radio-button">
                      <label for="user_gender_une_femme">Une femme</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Une femme" name="user[gender]" id="user_gender_une_femme">
                    </span>
                  </div>
                </div>
              </div>

              <div class="row">
                <div class="form col-xs-12 col-md-6">
                  <%= f.input :first_name, label: "Prénom" %>
                </div>
                <div class="form col-xs-12 col-md-6">
                  <%= f.input :last_name, label: "Nom" %>
                </div>
              </div>
              <%= f.input :birth_year, label: "Année de naissance", input_html: { value: 2017, min: 1900, max: 2017, class: "form-sm-input"} %>
              <%= f.input :phone_number, label: "Téléphone", placeholder: "0600000000", input_html: {class: "form-sm-input"} %>
              <%= f.input :description, label: "Description", placeholder: "Afin de mettre toutes les chances de votre côté, vous pouvez vous décrire en quelques lignes." %>

              <div class="form-group radio_buttons optional user_status">
                <label class="control-label radio_buttons optional">Votre activité</label>
                <input type="hidden" name="user[status]" value="">
                <div class="row text-center">
                  <div class="col-xs-6 col-md-3">
                    <span class="radio status-tenant-radio-button">
                      <label for="user_status_etudiant">Etudiant</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Etudiant" name="user[status]" id="user_status_etudiant">
                    </span>
                  </div>
                  <div class="col-xs-6 col-md-3">
                    <span class="radio status-tenant-radio-button">
                      <label for="user_status_salari">Salarié</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Salarié" name="user[status]" id="user_status_salari">
                    </span>
                  </div>
                  <div class="col-xs-6 col-md-3">
                    <span class="radio status-tenant-radio-button">
                      <label for="user_status_indpendant">Indépendant</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Indépendant" name="user[status]" id="user_status_indpendant">
                    </span>
                  </div>
                  <div class="col-xs-6 col-md-3">
                    <span class="radio status-tenant-radio-button">
                      <label for="user_status_autre">Autre</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Autre" name="user[status]" id="user_status_autre">
                    </span>
                  </div>
                </div>
              </div>

              <%= f.input :income, label: "Revenu net mensuel", input_html: { min: 0, step: 'any', class: "form-sm-input" } %>

              <div class="form-group boolean optional user_has_warrantor">
                <div class="checkbox hidden">
                  <label class="boolean optional" for="user_has_warrantor">Has warrantor</label>
                  <input value="0" type="hidden" id="user_has_warrantor" name="user[has_warrantor]">
                  <input class="boolean optional" type="checkbox" value="1" checked="checked" name="user[has_warrantor]" id="user_has_warrantor">
                </div>
              </div>


              <div class="form-group radio_buttons optional user_warrantor_type">
                <label class="control-label radio_buttons optional">Garant</label>
                <input type="hidden" name="user[warrantor_type]" value="">
                <div class="row">
                  <div class="col-xs-6 col-md-3">
                    <span class="radio status-tenant-radio-button">
                      <label for="user_warrantor_type_famille">Famille</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Famille" name="user[warrantor_type]" id="user_warrantor_type_famille">
                    </span>
                  </div>

                  <div class="col-xs-6 col-md-3">
                    <span class="radio status-tenant-radio-button">
                      <label for="user_warrantor_type_amis">Amis</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Amis" name="user[warrantor_type]" id="user_warrantor_type_amis">
                    </span>
                  </div>

                  <div class="col-xs-6 col-md-3">
                    <span class="radio status-tenant-radio-button">
                      <label for="user_warrantor_type_banque">Banque</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Banque" name="user[warrantor_type]" id="user_warrantor_type_banque">
                    </span>
                  </div>

                  <div class="col-xs-6 col-md-3">
                    <span class="radio status-tenant-radio-button">
                      <label for="user_warrantor_type_employeur">Employeur</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Employeur" name="user[warrantor_type]" id="user_warrantor_type_employeur">
                    </span>
                  </div>

                  <div class="col-xs-6 col-md-3">
                    <span class="radio status-tenant-radio-button">
                      <label for="user_warrantor_type_organisme">Organisme</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Organisme" name="user[warrantor_type]" id="user_warrantor_type_organisme">
                    </span>
                  </div>

                  <div class="col-xs-6 col-md-3">
                    <span class="radio status-tenant-radio-button" id="warrantor_type_none">
                      <label for="user_warrantor_type_autre">Aucun</label>
                      <input class="radio_buttons optional hidden" type="radio" value="Aucun" name="user[warrantor_type]" id="user_warrantor_type_autre">
                    </span>
                  </div>
                </div>
                </div>

              <%= f.input :warrantor_income, label: "Revenu net mensuel", input_html: { min: 0, step: 'any', class: "form-sm-input" } %>
            </div>

            <!-- Form actions -->
            <div class="form-actions text-center">
              <%= f.button :submit, "Renseigner mon profil", class:"btn btn-red"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>


<% content_for(:after_js) do %>
  <script>
    $(document).ready(function() {
      // Add active class to radio buttons
      $(".tenant-radio-button").click(function(){
       $(".tenant-radio-button").removeClass("active");
       $(this).toggleClass("active");
      });

      $(".status-tenant-radio-button").click(function(){
       $(".status-tenant-radio-button").removeClass("active");
       $(this).toggleClass("active");
      // Add value to has_warrantor if warrantor status is none
      if ($("#warrantor_type_none").hasClass("active")) {
        document.getElementById("user_has_warrantor").value = 0;
      } else {
        document.getElementById("user_has_warrantor").value = 1;
      }
      });

    });
  </script>
<% end %>

app/views/users/recherche.html.erb
<!-- Locataire navbar -->
<div class="navbar-flat navbar-flat-wagon-fixed">
  <div class="navbar-flat-content">
    <div class="<%= 'active' if current_page?(user_locataire_path(@user)) %>">
      <%= link_to "Mon profil", user_locataire_path(@user), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(user_recherche_path(@user)) %>">
      <%= link_to "Critères de recherche", user_recherche_path(@user), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flats_path) %>">
      <%= link_to "Annonces", flats_path, class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(user_visites_path(@user)) %>">
      <%= link_to "Visites", user_visites_path(@user), class: "navbar-wagon-link" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="card col-xs-12">
      <div class="row">
        <div class="form col-xs-12 col-md-6 col-md-offset-3">
          <h2 class="text-center sm-marged-bottom highlight">Ma recherche d'appartement</h2>
          <%= simple_form_for [@user, @search], url: user_recherche_path(@user) do |f| %>
            <%= f.error_notification %>

            <!-- Form inputs -->
            <div class="form-inputs">
              <%= f.input :address, label: "Adresse", placeholder: "Adresse, code postal, ville" %>
              <!-- <div id ='search-address-map', style="width: 100%; height: 400px;"></div> -->
              <div class="row">
                <div class="col-xs-12 col-md-6">
                  <%= f.input :size_min, label: "Superficie minimum", input_html: { min: 0, class: "form-sm-input"} %>
                </div>
                <div class="col-xs-12 col-md-6">
                  <%= f.input :rent_max, label: "Loyer maximum", input_html: { min: 0, class: "form-sm-input"} %>
                </div>
              </div>
            </div>

            <!-- Form actions -->
            <div class="form-actions text-center">
              <%= f.button :submit, "Rechercher mon appartement", class:"btn btn-red"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/visites.html.erb
<!-- Locataire navbar -->
<div class="navbar-flat navbar-flat-wagon-fixed">
  <div class="navbar-flat-content">
    <div class="<%= 'active' if current_page?(user_locataire_path(@user)) %>">
      <%= link_to "Mon profil", user_locataire_path(@user), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(user_recherche_path(@user)) %>">
      <%= link_to "Critères de recherche", user_recherche_path(@user), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flats_path) %>">
      <%= link_to "Annonces", flats_path, class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(user_visites_path(@user)) %>">
      <%= link_to "Visites", user_visites_path(@user), class: "navbar-wagon-link" %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="card col-xs-12">
      <div class="row">
        <h2 class="text-center sm-marged-bottom highlight">Mes visites</h2>

        <!-- Next slots -->
        <% @user.slots.order("starts_at asc").where(["status <> 'Cancelled'"]).where(['starts_at >= ?', DateTime.now.midnight]).group_by{|slot| slot.starts_at.strftime("%A %e %B %Y")}.each do |date, slots| %>
          <h4><strong><%= date %></strong></h4>
          <div class="row">
            <% slots.each do |slot| %>
              <%= link_to flat_path(slot.flat) do %>
                <div class="col-xs-12 col-sm-4 sm-marged-bottom">
                  <div class="card-dashboard">
                    <div class="card-dashboard-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%=slot.flat.photos.first.nil? ? "" : (cl_image_path slot.flat.photos.first.public_id , crop: :scale) %>);">
                      <% if slot.flat.slots.size == 0 %>
                        <div class="card-category badge-red">Visites en cours</div>
                      <% end %>
                    </div>
                    <div class="card-dashboard-description ">
                      <h2 class="highlight" style="height: 40px; margin-bottom: 20px"><%= slot.flat.title %></h2>
                      <p>
                        <%= slot.flat.size %>m²
                        <br>
                        <%= slot.flat.rent + slot.flat.rental_costs %>€/mois
                        <br>
                        Visite le <%= slot.starts_at.strftime("%d/%m/%Y") %>
                      </p>
                    </div>
                  </div>
                </div>
              <% end %>
            <% end %>
          </div>
        <% end %>

        <!-- Past slots -->
        <% if @user.slots.order("starts_at asc").where(['starts_at < ?', DateTime.now.midnight]).length >= 1 %>
          <% @user.slots.order("starts_at asc").where(['starts_at < ?', DateTime.now.midnight]).group_by{|slot| slot.starts_at.strftime("%A %e %B %Y")}.each do |date, slots| %>
            <h4><strong><%= date %></strong></h4>
            <div class="row">
              <% slots.each do |slot| %>
                <%= link_to flat_path(slot.flat) do %>
                  <div class="col-xs-12 col-sm-4 sm-marged-bottom">
                    <div class="card-dashboard">
                      <div class="card-dashboard-image" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url(<%=slot.flat.photos.first.nil? ? "" : (cl_image_path slot.flat.photos.first.public_id , crop: :scale) %>);">
                        <% if slot.flat.slots.size == 0 %>
                          <div class="card-category badge-red">Visites en cours</div>
                        <% end %>
                      </div>
                      <div class="card-dashboard-description ">
                        <h2 class="highlight" style="height: 40px; margin-bottom: 20px"><%= slot.flat.title %></h2>
                        <p>
                          <%= slot.flat.size %>m²
                          <br>
                          <%= slot.flat.rent + slot.flat.rental_costs %>€/mois
                          <br>
                          Visite le <%= slot.starts_at.strftime("%d/%m/%Y") %>
                        </p>
                      </div>
                    </div>
                  </div>
                <% end %>
              <% end %>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>