config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
    controllers: {
      registrations: "users/registrations"
    }

  root to: 'pages#home'

  resources :flats do
    get "visits" => "flats#visits" # Visits for landlords
    get "candidates" => "flats#candidates"
    patch "filter" => "flats#filter"
    get "etat_des_lieux" => "flats#etat_des_lieux"

    resources :slots, only: [:create, :update, :destroy] do
      patch "slot_confirm" => "slots#slot_confirm"
      patch "slot_cancel" => "slots#slot_cancel"
    end

    resources :bookings, only: [] do
      patch "booking_confirm" => "bookings#booking_confirm"
      patch "booking_cancel" => "bookings#booking_cancel"
      resources :documents, only: [:show, :index, :create, :update]
    end
  end

  resources :searches, only: [:new, :create, :edit, :update]

  get "profile" => "pages#profile"
  get "dashboard" => "pages#dashboard"
  get "visites" => "pages#visites" # Visits for tenants

  mount Attachinary::Engine => "/attachinary"
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :booking, foreign_key: :booking_id, class_name: "Booking"

  validates :title, presence: true
  validates :document_type, presence: true, inclusion: { in: ["Etat des lieux", "Bail", "Quittance"] }
  validates :status, presence: true, inclusion: { in: ["Signatures manquantes", "Signé", "Emis"] }
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  def show
    @document = Document.find(params[:id])
    @booking = Booking.find(@document.booking_id)
    authorize @document

    if @document.document_type == "Bail"
      respond_to do |format|
        format.pdf do
          render pdf: "bail.pdf",
                 template: "documents/bail.pdf.erb"
        end
      end
    elsif @document.document_type == "Etat des lieux"
      respond_to do |format|
        format.pdf do
          render pdf: "etat_des_lieux.pdf",
                 template: "documents/etat_des_lieux.pdf.erb"
        end
      end
    elsif @document.document_type == "Quittance"
      respond_to do |format|
        format.pdf do
          render pdf: "quittance.pdf",
                 template: "documents/quittance.pdf.erb"
        end
      end
    end
  end

  def index
    @flat = Flat.find(params[:flat_id])
    @booking = @flat.bookings.where(status: "Confirmed").last
    @documents = policy_scope(Document).where(booking_id: @booking)
  end

  def create
  end

  def update
  end

end

app/views/documents/_bail.html.erb
<% if @booking.flat.furnished %>
  <div class="container">
    <h2 class="highlight text-center"><strong>CONTRAT DE <%= @booking.flat.rental_type.upcase %> DE LOGEMENT MEUBLE</strong></h2>

    <h4 class="highlight"><strong>I. Désignation des parties</strong></h2>
    <p>
      Le présent contrat est conclu entre les soussignés :
      <br>
      <ul>
        <li>
          <%= @booking.flat.landlord.first_name %> <%= @booking.flat.landlord.last_name %>, personne physique (adresse électronique : <%= @booking.flat.landlord.email %>), désigné ci-après « le bailleur » ;
        </li>
        <li>
          <%= @booking.tenant.first_name %> <%= @booking.tenant.last_name %>, personne physique (adresse électronique : <%= @booking.tenant.email %>), désigné ci-après « le locataire » ;
        </li>
      </ul>
      Il a été convenu ce qui suit :
      <br>
    </p>
    <br>
    <br>

    <h4 class="highlight"><strong>II. Objet du contrat</strong></h2>
    <p>
      Le présent contrat a pour objet la location d’un logement ainsi déterminé :
    </p>
    <p>
    A. Consistance du logement
    <ul>
      <li>
        localisation du logement : <%= @booking.flat.address %> ;
      </li>
      <li>
        surface habitable : <%= @booking.flat.size %> m2 ;
      </li>
      <li>
        nombre de pièces principales : <%= @booking.flat.rooms %> ;
      </li>
    </ul>

    B. Destination des locaux : usage d’habitation
    <br>

    <% if @booking.flat.parking && @booking.flat.elevator  %>
        C. Equipement accessoire de l’immeuble à usage privatif du locataire :
        <ul>
          <li>
            Parking.
          </li>
        </ul>
        D. Equipement de l’immeuble à usage commun :
        <ul>
          <li>
            Ascenseur.
          </li>
        </ul>
      <% elsif @booking.flat.parking %>
        C. Equipement accessoire de l’immeuble à usage privatif du locataire :
        <ul>
          <li>
            Parking.
          </li>
        </ul>
      <% elsif @booking.flat.elevator %>
        C. Equipement de l’immeuble à usage commun :
        <ul>
          <li>
            Ascenseur.
          </li>
        </ul>
      <% end %>
      <br>
    </p>

    <h4 class="highlight"><strong>III. Date de prise d’effet et durée du contrat</strong></h2>
      <p>
        La durée du contrat et sa date de prise d’effet sont ainsi définies :
        <br>
        A. Date de prise d’effet du contrat : <%= @booking.flat.availability_date.strftime("%d/%m/%Y") %>
        <br>
        B. Durée du contrat : <%= [@booking.flat.min_duration, 12].min %> mois
        <br>
        Les contrats de location de logements meublés sont reconduits tacitement à leur terme pour une durée d’un an et
        dans les mêmes conditions. Le locataire peut mettre fin au bail à tout moment, après avoir donné
        congé. Le bailleur peut, quant à lui, mettre fin au bail à son échéance et après avoir donné congé, soit
        pour reprendre le logement en vue de l’occuper lui-même ou une personne de sa famille, soit pour le
        vendre, soit pour un motif sérieux et légitime.
      </p>
      <br>

    <h4 class="highlight"><strong>IV. Conditions financières</strong></h2>
    <p>
      Les parties conviennent des conditions financières suivantes :
    </p>

    <p>
      A. Loyer
      <br>
      1. Fixation du loyer initial :
      <br>
      Montant du loyer mensuel : <%= @booking.flat.rent %> €
    </p>

    <p>
      2. Modalités de révision :
      <br>
      a) Date de révision : <%= (@booking.flat.availability_date + 1.years).strftime("%d/%m/%Y") %>
      <br>
      b) Date ou trimestre de référence de l’IRL : 2ème trimestre 2017
      <br>
    </p>

    <p>
      B. Charges récupérables
      <br>
      1. Modalité de règlement des charges récupérables : provisions sur charges avec régularisation annuelle
      <br>
      2. Montant des provisions sur charges ou du forfait de charges: <%= @booking.flat.rental_costs %> €
      <br>
    </p>

    <p>
      C. Modalités de paiement
      <ul>
        <li>
          Périodicité du paiement : mensuelle
        </li>
        <li>
          Paiement à terme échu
        </li>
        <li>
          Date : 1er de chaque mois
        </li>
        <li>
          Montant total dû à la première échéance de paiement pour une période complète de location :
          <ul>
            <li>
              somme des montants relatifs au loyer : <%= @booking.flat.rent %> €
            </li>
            <li>
              charges récupérables : <%= @booking.flat.rental_costs %> €
            </li>
          </ul>
        </li>
      </ul>
    </p>

    <h4 class="highlight"><strong>V. Garanties</strong></h2>
      <p>
        Le cas échéant, Montant du dépôt de garantie de l’exécution des obligations du locataire : [inférieur ou égal
        à deux mois de loyers hors charges] : <%= @booking.flat.deposit %> €
      </p>

    <h4 class="highlight"><strong>VI. Clause résolutoire</strong></h2>
      <p>
        Modalités de résiliation de plein droit du contrat : défaut de paiement du loyer ou des charges aux termes
        convenus, non versement du dépôt de garantie, non-souscription d’une assurance des
        risques locatifs ou le non-respect de l’obligation d’user paisiblement des locaux loués, résultant
        de troubles de voisinage constatés par une décision de justice passée en force de chose
        jugée
      </p>

      <p>
        Fait à Paris, le <%= @document.creation_date %>
        <br>
        <br>
        Signature du bailleur
        <br>
        <br>
        Signature du locataire
        <br>
      </p>
  </div>
<% else %>
  <div class="container">
    <h2 class="highlight text-center"><strong>CONTRAT DE <%= @booking.flat.rental_type.upcase %> DE LOGEMENT MEUBLE</strong></h2>

    <h4 class="highlight"><strong>I. Désignation des parties</strong></h2>
    <p>
      Le présent contrat est conclu entre les soussignés :
      <br>
      <ul>
        <li>
          <%= @booking.flat.landlord.first_name %> <%= @booking.flat.landlord.last_name %>, personne physique (adresse électronique : <%= @booking.flat.landlord.email %>), désigné ci-après « le bailleur » ;
        </li>
        <li>
          <%= @booking.tenant.first_name %> <%= @booking.tenant.last_name %>, personne physique (adresse électronique : <%= @booking.tenant.email %>), désigné ci-après « le locataire » ;
        </li>
      </ul>
      Il a été convenu ce qui suit :
      <br>
    </p>
    <br>
    <br>

    <h4 class="highlight"><strong>II. Objet du contrat</strong></h2>
    <p>
      Le présent contrat a pour objet la location d’un logement ainsi déterminé :
    </p>
    <p>
    A. Consistance du logement
    <ul>
      <li>
        localisation du logement : <%= @booking.flat.address %> ;
      </li>
      <li>
        surface habitable : <%= @booking.flat.size %> m2 ;
      </li>
      <li>
        nombre de pièces principales : <%= @booking.flat.rooms %> ;
      </li>
    </ul>

    B. Destination des locaux : usage d’habitation
    <br>

    <% if @booking.flat.parking && @booking.flat.elevator  %>
        C. Equipement accessoire de l’immeuble à usage privatif du locataire :
        <ul>
          <li>
            Parking.
          </li>
        </ul>
        D. Equipement de l’immeuble à usage commun :
        <ul>
          <li>
            Ascenseur.
          </li>
        </ul>
      <% elsif @booking.flat.parking %>
        C. Equipement accessoire de l’immeuble à usage privatif du locataire :
        <ul>
          <li>
            Parking.
          </li>
        </ul>
      <% elsif @booking.flat.elevator %>
        C. Equipement de l’immeuble à usage commun :
        <ul>
          <li>
            Ascenseur.
          </li>
        </ul>
      <% end %>
      <br>
    </p>

    <h4 class="highlight"><strong>III. Date de prise d’effet et durée du contrat</strong></h2>
      <p>
        La durée du contrat et sa date de prise d’effet sont ainsi définies :
        <br>
        A. Date de prise d’effet du contrat : <%= @booking.flat.availability_date.strftime("%d/%m/%Y") %>
        <br>
        B. Durée du contrat : durée minimale de trois ou six ans
        <br>
        En l’absence de proposition de renouvellement du contrat, celui-ci est, à sont terme, reconduit
        tacitement pour 3 ou 6 ans et dans les mêmes conditions. Le locataire peut mettre fin au bail à tout
        moment, après avoir donné congé. Le bailleur, quant à lui, peut mettre fin au bail à son échéance
        et après avoir donné congé, soit pour reprendre le logement en vue de l’occuper lui-même ou une
        personne de sa famille, soit pour le vendre, soit pour un motif sérieux et légitime.
      </p>
      <br>

    <h4 class="highlight"><strong>IV. Conditions financières</strong></h2>
    <p>
      Les parties conviennent des conditions financières suivantes :
    </p>

    <p>
      A. Loyer
      <br>
      1. Fixation du loyer initial :
      <br>
      Montant du loyer mensuel : <%= @booking.flat.rent %> €
    </p>

    <p>
      2. Modalités de révision :
      <br>
      a) Date de révision : <%= (@booking.flat.availability_date + 1.years).strftime("%d/%m/%Y") %>
      <br>
      b) Date ou trimestre de référence de l’IRL : 2ème trimestre 2017
      <br>
    </p>

    <p>
      B. Charges récupérables
      <br>
      1. Modalité de règlement des charges récupérables : provisions sur charges avec régularisation annuelle
      <br>
      2. Montant des provisions sur charges ou du forfait de charges: <%= @booking.flat.rental_costs %> €
      <br>
    </p>

    <p>
      C. Modalités de paiement
      <ul>
        <li>
          Périodicité du paiement : mensuelle
        </li>
        <li>
          Paiement à terme échu
        </li>
        <li>
          Date : 1er de chaque mois
        </li>
        <li>
          Montant total dû à la première échéance de paiement pour une période complète de location :
          <ul>
            <li>
              somme des montants relatifs au loyer : <%= @booking.flat.rent %> €
            </li>
            <li>
              charges récupérables : <%= @booking.flat.rental_costs %> €
            </li>
          </ul>
        </li>
      </ul>
    </p>

    <h4 class="highlight"><strong>V. Garanties</strong></h2>
      <p>
        Le cas échéant, Montant du dépôt de garantie de l’exécution des obligations du locataire : [inférieur ou égal
        à deux mois de loyers hors charges] : <%= @booking.flat.deposit %> €
      </p>

    <h4 class="highlight"><strong>VI. Clause résolutoire</strong></h2>
      <p>
        Modalités de résiliation de plein droit du contrat : défaut de paiement du loyer ou des charges aux termes
        convenus, non versement du dépôt de garantie, non-souscription d’une assurance des
        risques locatifs ou le non-respect de l’obligation d’user paisiblement des locaux loués, résultant
        de troubles de voisinage constatés par une décision de justice passée en force de chose
        jugée
      </p>

      <p>
        Fait à Paris, le <%= @document.creation_date %>
        <br>
        <br>
        Signature du bailleur
        <br>
        <br>
        Signature du locataire
        <br>
      </p>
  </div>
<% end %>

app/views/documents/_etat_des_lieux.html.erb
<div class="container">
  <h2 class="highlight text-center"><strong>Etat des lieux</strong></h2>

  <%= simple_form_for :etat_des_lieux do |f| %>
    <%= f.error_notification %>
    <%= f.full_error :confirmation_token %>

    <div class="form-inputs">
    </div>

    <div class="form-actions">
      <%= f.button :submit, "Soumettre mon inventaire", class:"btn btn-red" %>
    </div>
  <% end %>

  <p>
    Nombre de pièces
    Photos
    Etat string ["Mauvais état", "Bon état", "Très bon état"]
    Description text
    Mur A
    Mur B
    Mur C
    Mur D
    Plaintes

    Date
    Signature
  </p>
</div>

app/views/documents/_quittance.html.erb
<div class="container">
  <h2 class="highlight text-center"><strong>QUITTANCE DE LOYER - MAI 2017</strong></h2>
  <p>
    <strong>Émetteur :</strong> <%= @booking.flat.landlord.first_name %> <%= @booking.flat.landlord.last_name %>
    <br>
    <strong>Téléphone :</strong> <%= @booking.flat.landlord.phone_number %>
    <br>
    <strong>Email :</strong> <%= @booking.flat.landlord.email %>
    <br>
    <br>

    <span>
      Je soussigné
      <% if @booking.flat.landlord.gender.nil? %>
        (e)
      <% elsif @booking.flat.landlord.gender == "Homme" %>
      <% elsif @booking.flat.landlord.gender == "Femme" %>
        e
      <% end %>
    </span>
     : <%= @booking.flat.landlord.first_name %> <%= @booking.flat.landlord.last_name %>,
    <br>
    <br>
    certifie que
    <% if @booking.tenant.gender.nil? %>
    <% elsif @booking.tenant.gender == "Homme" %>
      Monsieur
    <% elsif @booking.tenant.gender == "Femme" %>
      Madame
    <% end %>
    <%= @booking.tenant.first_name %> <%= @booking.tenant.last_name %>,
    locataire, depuis le <%= @booking.flat.availability_date.strftime("%d/%m/%Y") %>,
    d'un logement, sise <%= @booking.flat.address %>,
    est à jour du règlement du loyer d'un montant mensuel de
    <%= @booking.flat.rent %> euros
    et des charges locatives d'un montant mensuel de
    <%= @booking.flat.rental_costs %> euros.
    <br>
    <br>
    Fait à Paris, le <%= @document.creation_date %>
    <br>
    <br>
    <br>
    Signature
  </p>
</div>

app/views/documents/index.html.erb
<!-- Flat navbar -->
<div class="navbar-flat navbar-flat-wagon-fixed">
  <div class="navbar-flat-content">
    <div class="<%= 'active' if current_page?(flat_visits_path(@flat)) %>">
      <%= link_to "Visites", flat_visits_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_candidates_path(@flat)) %>">
      <%= link_to "Candidats", flat_candidates_path(@flat), class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?(flat_booking_documents_path(@flat, @flat.bookings.where(status: "Confirmed"))) %>">
      <%= link_to "Docs", flat_booking_documents_path(@flat, @flat.bookings.where(status: "Confirmed")), class: "navbar-wagon-link" %>
    </div>
  </div>
</div>

<!-- Document tabs -->
<div class="navbar-flat navbar-flat-wagon-fixed">
  <div class="navbar-flat-content">
    <div class="<%= 'active' if current_page?("#") %>">
      <%= link_to "Etat des lieux", "#", class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?("#") %>">
      <%= link_to "Bail", "#", class: "navbar-wagon-link" %>
    </div>
    <div class="<%= 'active' if current_page?("#") %>">
      <%= link_to "Quittances", "#", class: "navbar-wagon-link" %>
    </div>
  </div>
</div>

<!-- Etat des lieux -->
<div class="hidden">
  <div class="container card text-center marged-top">
    <h2 class="highlight">Etat des lieux</h2>
    <% render "documents/etat_des_lieux" %>
  </div>
</div>

<!-- Bail -->
<div class="container card text-center marged-top">
  <% if @documents.where(document_type:"Bail").size == 0 %>
    <h2 class="highlight">Bail immobilier</h2>
    <p>Nous attendons que la demande de réservation soit confirmée avant de générer un bail.</p>
  <% else %>
    <h2 class="highlight">Bail immobilier</h2>

    <% @documents.where(document_type:"Bail").each do |document| %>
      <div class="card">
        <div class="row">
          <div class="col-xs-6">
            <strong><%= document.title %></strong>
          </div>
          <div class="col-xs-2">
            <span class="highlight"><b><%= document.status %></b></span>
          </div>
          <div class="col-xs-2">
            <%= document.created_at.strftime("%d/%m/%Y") %>
          </div>
          <div class="col-xs-2">
            <%= link_to flat_booking_document_path(@flat, @booking, document, format: 'pdf') do %>
              <i class="fa fa-arrow-circle-o-down" aria-hidden="true"></i>
            <% end %>
          </div>
        </div>
        <div class="line-separator"></div>
      </div>
    <% end %>
  <% end %>
</div>

<!-- Quittances de loyer  -->
<div class="container card text-center marged-top">
  <% if @documents.where(document_type:"Quittance").size == 0 %>
    <h2 class="highlight">Quittances de loyer</h2>
    <p>Nous attendons que le bail soit signé avant de générer la première quittance de loyer.</p>
  <% else %>
    <h2 class="highlight">Quittances de loyer</h2>

    <% @documents.where(document_type:"Quittance").each do |document| %>
      <div class="card">
        <div class="row">
          <div class="col-xs-6">
            <strong><%= document.title %></strong>
          </div>
          <div class="col-xs-2">
            <span class="highlight"><b><%= document.status %></b></span>
          </div>
          <div class="col-xs-2">
            <%= document.created_at.strftime("%d/%m/%Y") %>
          </div>
          <div class="col-xs-2">
            <%= link_to flat_booking_document_path(@flat, @booking, document, format: 'pdf') do %>
              <i class="fa fa-arrow-circle-o-down" aria-hidden="true"></i>
            <% end %>
          </div>
        </div>
        <div class="line-separator"></div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/documents/quittance.pdf.erb
<head>
  <meta charset='utf-8' />
  <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
  <%= wicked_pdf_javascript_include_tag "number_pages" %>
</head>

<div class="container">
  <h2 class="highlight text-center"><strong>QUITTANCE DE LOYER - MAI 2017</strong></h2>
  <p>
    <strong>Émetteur :</strong> <%= @booking.flat.landlord.first_name %> <%= @booking.flat.landlord.last_name %>
    <br>
    <strong>Téléphone :</strong> <%= @booking.flat.landlord.phone_number %>
    <br>
    <strong>Email :</strong> <%= @booking.flat.landlord.email %>
    <br>
    <br>

    <span>
      Je soussigné
      <% if @booking.flat.landlord.gender.nil? %>
        (e)
      <% elsif @booking.flat.landlord.gender == "Homme" %>
      <% elsif @booking.flat.landlord.gender == "Femme" %>
        e
      <% end %>
    </span>
     : <%= @booking.flat.landlord.first_name %> <%= @booking.flat.landlord.last_name %>,
    <br>
    <br>
    certifie que
    <% if @booking.tenant.gender.nil? %>
    <% elsif @booking.tenant.gender == "Homme" %>
      Monsieur
    <% elsif @booking.tenant.gender == "Femme" %>
      Madame
    <% end %>
    <%= @booking.tenant.first_name %> <%= @booking.tenant.last_name %>,
    locataire, depuis le <%= @booking.flat.availability_date.strftime("%d/%m/%Y") %>,
    d'un logement, sise <%= @booking.flat.address %>,
    est à jour du règlement du loyer d'un montant mensuel de
    <%= @booking.flat.rent %> euros
    et des charges locatives d'un montant mensuel de
    <%= @booking.flat.rental_costs %> euros.
    <br>
    <br>
    Fait à Paris, le <%= @document.creation_date %>
    <br>
    <br>
    <br>
    Signature
  </p>
</div>

app/views/documents/show.html.erb
<% if @document.document_type == "Bail"  %>
  <%= render "documents/bail" %>
<% elsif @document.document_type == "Etat des lieux" %>
  <%= render "documents/etat_des_lieux" %>
<% elsif @document.document_type == "Quittance" %>
  <%= render "documents/quittance" %>
<% end %>